"""Add inference data model

Revision ID: 077c4f22ff0b
Revises: 41218b8dac5c
Create Date: 2025-12-11 18:03:55.787868

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "077c4f22ff0b"
down_revision: Union[str, Sequence[str], None] = "41218b8dac5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operating_systems_percentage", sa.Integer(), nullable=False),
        sa.Column("algorithms_percentage", sa.Integer(), nullable=False),
        sa.Column("programming_concepts_percentage", sa.Integer(), nullable=False),
        sa.Column("software_engineering_percentage", sa.Integer(), nullable=False),
        sa.Column("electronics_subjects_percentage", sa.Integer(), nullable=False),
        sa.Column("computer_architecture_percentage", sa.Integer(), nullable=False),
        sa.Column("mathematics_percentage", sa.Integer(), nullable=False),
        sa.Column("communication_skills_percentage", sa.Integer(), nullable=False),
        sa.Column("hours_working_per_day", sa.Integer(), nullable=False),
        sa.Column("logical_quotient_rating", sa.Integer(), nullable=False),
        sa.Column("hackathons", sa.Integer(), nullable=False),
        sa.Column("coding_skills_rating", sa.Integer(), nullable=False),
        sa.Column("public_speaking_points", sa.Integer(), nullable=False),
        sa.Column(
            "can_work_long_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "self_learning_capability",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "extra_courses_did", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("certifications", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workshops", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "talent_tests_taken", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("olympiads", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reading_writing_skills", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "memory_capability_score",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "interested_subjects", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "interested_career_area", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "job_higher_studies", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "company_type_prefered", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "taken_inputs_from_elders",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "interested_in_games", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "interested_book_types", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "salary_range_expected", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "in_realtionship", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("behaviour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "management_or_technical",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("worker_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_work", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrovert", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inference_data")
    # ### end Alembic commands ###
