"""Add ml_request model

Revision ID: 110237db23da
Revises: 688909dcb3c0
Create Date: 2025-12-02 16:00:16.002315

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110237db23da'
down_revision: Union[str, Sequence[str], None] = '688909dcb3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ml_model_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_model.id'], name='fk_ml_model_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ml_request_transaction', sa.Column('ml_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_ml_request_id', 'ml_request_transaction', 'ml_request', ['ml_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ml_request_id', 'ml_request_transaction', type_='foreignkey')
    op.drop_column('ml_request_transaction', 'ml_request_id')
    op.drop_table('ml_request')
    # ### end Alembic commands ###
