"""Add balance model

Revision ID: 39483530d83a
Revises: 30aa90ac7543
Create Date: 2025-12-02 15:47:44.486615

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39483530d83a'
down_revision: Union[str, Sequence[str], None] = '30aa90ac7543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('balance_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_balance_id', 'user', 'balance', ['balance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_balance_id', 'user', type_='foreignkey')
    op.drop_column('user', 'balance_id')
    op.drop_table('balance')
    # ### end Alembic commands ###
