"""Add person model

Revision ID: 41218b8dac5c
Revises: 6fe96ffbae47
Create Date: 2025-12-11 18:02:01.273887

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41218b8dac5c"
down_revision: Union[str, Sequence[str], None] = "6fe96ffbae47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="role"), nullable=False),
        sa.Column("balance_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["balance_id"], ["balance.id"], name="fk_balance_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person")
    sa.Enum("USER", "ADMIN", name="role").drop(op.get_bind())
    # ### end Alembic commands ###
