"""Add deposit request model

Revision ID: 46a6dd8ddd17
Revises: a8c79643d0fd
Create Date: 2025-12-27 15:06:05.394929

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46a6dd8ddd17"
down_revision: Union[str, Sequence[str], None] = "a8c79643d0fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "deposit_status",
            sa.Enum("QUEUED", "COMPLETED", "FAILED", "REJECTED", name="depositstatus"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], name="fk_person_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deposit_request")
    sa.Enum("QUEUED", "COMPLETED", "FAILED", "REJECTED", name="depositstatus").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
