"""Add ml model model

Revision ID: 46baad9e7249
Revises: 6c1f81603d9e
Create Date: 2025-12-11 18:10:39.698019

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46baad9e7249"
down_revision: Union[str, Sequence[str], None] = "6c1f81603d9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("request_cost", sa.Float(), nullable=False),
        sa.Column("model_path", sa.VARCHAR(), nullable=False),
        sa.Column("preprocessing_path", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_model")
    # ### end Alembic commands ###
