"""Add ml_model model

Revision ID: 688909dcb3c0
Revises: c7f5cfee7ec3
Create Date: 2025-12-02 15:56:01.453804

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688909dcb3c0'
down_revision: Union[str, Sequence[str], None] = 'c7f5cfee7ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_cost', sa.Float(), nullable=False),
    sa.Column('model_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preprocessing_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_model')
    # ### end Alembic commands ###
