"""Add ml request model

Revision ID: 6bdace7f6551
Revises: de8ab54dc6dc
Create Date: 2025-12-11 18:13:19.276209

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bdace7f6551"
down_revision: Union[str, Sequence[str], None] = "de8ab54dc6dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("credits_used", sa.Float(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ml_model_id", sa.UUID(), nullable=True),
        sa.Column("inference_data_id", sa.UUID(), nullable=True),
        sa.Column("response_data_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inference_data_id"], ["inference_data.id"], name="fk_inference_data_id"
        ),
        sa.ForeignKeyConstraint(
            ["ml_model_id"], ["ml_model.id"], name="fk_ml_model_id"
        ),
        sa.ForeignKeyConstraint(
            ["response_data_id"], ["response_data.id"], name="fk_response_data_id"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["person.id"], name="fk_person_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_request")
    # ### end Alembic commands ###
