"""Add response data model

Revision ID: 6c1f81603d9e
Revises: 077c4f22ff0b
Create Date: 2025-12-11 18:04:35.896973

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c1f81603d9e"
down_revision: Union[str, Sequence[str], None] = "077c4f22ff0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_role_result", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("response_data")
    # ### end Alembic commands ###
