"""Add data model

Revision ID: 6e0194b63423
Revises: 110237db23da
Create Date: 2025-12-02 16:02:33.121873

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e0194b63423"
down_revision: Union[str, Sequence[str], None] = "110237db23da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operating_systems_percentage", sa.Integer(), nullable=False),
        sa.Column("algorithms_percentage", sa.Integer(), nullable=False),
        sa.Column("programming_concepts_percentage", sa.Integer(), nullable=False),
        sa.Column("software_engineering_percentage", sa.Integer(), nullable=False),
        sa.Column("electronics_subjects_percentage", sa.Integer(), nullable=False),
        sa.Column("computer_architecture_percentage", sa.Integer(), nullable=False),
        sa.Column("mathematics_percentage", sa.Integer(), nullable=False),
        sa.Column("communication_skills_percentage", sa.Integer(), nullable=False),
        sa.Column("hours_working_per_day", sa.Integer(), nullable=False),
        sa.Column("logical_quotient_rating", sa.Integer(), nullable=False),
        sa.Column("hackathons", sa.Integer(), nullable=False),
        sa.Column("coding_skills_rating", sa.Integer(), nullable=False),
        sa.Column("public_speaking_points", sa.Integer(), nullable=False),
        sa.Column(
            "can_work_long_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "self_learning_capability",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "extra_courses_did", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("certifications", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workshops", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "talenttests_taken", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("olympiads", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reading_writing_skills", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "memory_capability_score",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "interested_subjects", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "interested_career_area", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "Job_higher_studies", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "company_type_prefered", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "taken_inputs_from_elders",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "interested_in_games", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "interested_book_types", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "salary_range_expected", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "in_realtionship", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("behaviour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "management_or_technical",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("worker_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_work", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrovert", sa.Boolean(), nullable=False),
        sa.Column(
            "job_role_result", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("ml_request", sa.Column("data_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_ml_data_id", "ml_request", "data", ["data_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_ml_data_id", "ml_request", type_="foreignkey")
    op.drop_column("ml_request", "data_id")
    op.drop_table("data")
    # ### end Alembic commands ###
