"""Add ml request transaction model

Revision ID: 78b8c69aff3d
Revises: 6bdace7f6551
Create Date: 2025-12-11 18:14:10.829375

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78b8c69aff3d"
down_revision: Union[str, Sequence[str], None] = "6bdace7f6551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_request_transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("ml_request_id", sa.UUID(), nullable=True),
        sa.Column("balance_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["balance_id"], ["balance.id"], name="fk_balance_id"),
        sa.ForeignKeyConstraint(
            ["ml_request_id"], ["ml_request.id"], name="fk_ml_request_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_request_transaction")
    # ### end Alembic commands ###
