"""Update ml model model

Revision ID: 859a25e80655
Revises: 78b8c69aff3d
Create Date: 2025-12-15 11:05:33.832793

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "859a25e80655"
down_revision: Union[str, Sequence[str], None] = "78b8c69aff3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_model",
        sa.Column(
            "label_encoder_path",
            sa.VARCHAR(),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model", "label_encoder_path")
    # ### end Alembic commands ###
