"""Update inference data model

Revision ID: a8c79643d0fd
Revises: c1b5d79130d1
Create Date: 2025-12-25 20:21:37.463600

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8c79643d0fd"
down_revision: Union[str, Sequence[str], None] = "c1b5d79130d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inference_data",
        sa.Column("computer_networks_percentage", sa.Integer(), nullable=False),
    )
    op.alter_column(
        "inference_data",
        "can_work_long_time",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="can_work_long_time::integer",
    )
    op.alter_column(
        "inference_data",
        "self_learning_capability",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="self_learning_capability::integer",
    )
    op.alter_column(
        "inference_data",
        "extra_courses_did",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="extra_courses_did::integer",
    )
    op.alter_column(
        "inference_data",
        "talent_tests_taken",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="talent_tests_taken::integer",
    )
    op.alter_column(
        "inference_data",
        "olympiads",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="olympiads::integer",
    )
    op.alter_column(
        "inference_data",
        "reading_writing_skills",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="reading_writing_skills::integer",
    )
    op.alter_column(
        "inference_data",
        "memory_capability_score",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="memory_capability_score::integer",
    )
    op.alter_column(
        "inference_data",
        "job_higher_studies",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="job_higher_studies::integer",
    )
    op.alter_column(
        "inference_data",
        "taken_inputs_from_elders",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="taken_inputs_from_elders::integer",
    )
    op.alter_column(
        "inference_data",
        "interested_in_games",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="interested_in_games::integer",
    )
    op.alter_column(
        "inference_data",
        "salary_range_expected",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="salary_range_expected::integer",
    )
    op.alter_column(
        "inference_data",
        "in_realtionship",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="in_realtionship::integer",
    )
    op.alter_column(
        "inference_data",
        "behaviour",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="behaviour::integer",
    )
    op.alter_column(
        "inference_data",
        "management_or_technical",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="management_or_technical::integer",
    )
    op.alter_column(
        "inference_data",
        "worker_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="worker_type::integer",
    )
    op.alter_column(
        "inference_data",
        "team_work",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="team_work::integer",
    )
    op.alter_column(
        "inference_data",
        "introvert",
        existing_type=sa.BOOLEAN(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="introvert::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema safely."""
    # Drop the newly added column
    op.drop_column("inference_data", "computer_networks_percentage")

    # Revert column types using explicit casting
    op.alter_column(
        "inference_data",
        "can_work_long_time",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="can_work_long_time::varchar",
    )
    op.alter_column(
        "inference_data",
        "self_learning_capability",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="self_learning_capability::varchar",
    )
    op.alter_column(
        "inference_data",
        "extra_courses_did",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="extra_courses_did::varchar",
    )
    op.alter_column(
        "inference_data",
        "talent_tests_taken",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="talent_tests_taken::varchar",
    )
    op.alter_column(
        "inference_data",
        "olympiads",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="olympiads::varchar",
    )
    op.alter_column(
        "inference_data",
        "reading_writing_skills",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="reading_writing_skills::varchar",
    )
    op.alter_column(
        "inference_data",
        "memory_capability_score",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="memory_capability_score::varchar",
    )
    op.alter_column(
        "inference_data",
        "job_higher_studies",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="job_higher_studies::varchar",
    )
    op.alter_column(
        "inference_data",
        "taken_inputs_from_elders",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="taken_inputs_from_elders::varchar",
    )
    op.alter_column(
        "inference_data",
        "interested_in_games",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="interested_in_games::varchar",
    )
    op.alter_column(
        "inference_data",
        "salary_range_expected",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="salary_range_expected::varchar",
    )
    op.alter_column(
        "inference_data",
        "in_realtionship",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="in_realtionship::varchar",
    )
    op.alter_column(
        "inference_data",
        "behaviour",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="behaviour::varchar",
    )
    op.alter_column(
        "inference_data",
        "management_or_technical",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="management_or_technical::varchar",
    )
    op.alter_column(
        "inference_data",
        "worker_type",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="worker_type::varchar",
    )
    op.alter_column(
        "inference_data",
        "team_work",
        type_=sa.VARCHAR(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="team_work::varchar",
    )
    op.alter_column(
        "inference_data",
        "introvert",
        type_=sa.BOOLEAN(),
        existing_type=sa.Integer(),
        existing_nullable=False,
        postgresql_using="introvert::boolean",
    )
    # ### end Alembic commands ###
