"""Update ml request model

Revision ID: c1b5d79130d1
Revises: 859a25e80655
Create Date: 2025-12-21 10:54:38.792861

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1b5d79130d1"
down_revision: Union[str, Sequence[str], None] = "859a25e80655"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="status")

    status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "ml_request",
        "status",
        existing_type=sa.VARCHAR(),
        type_=status_enum,
        existing_nullable=False,
        postgresql_using="status::status",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="status")
    op.alter_column(
        "ml_request",
        "status",
        existing_type=status_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="status::text",
    )
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
