"""Add transaction models

Revision ID: c7f5cfee7ec3
Revises: 39483530d83a
Create Date: 2025-12-02 15:53:52.185235

"""


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7f5cfee7ec3"
down_revision: Union[str, Sequence[str], None] = "39483530d83a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("balance_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["balance_id"], ["balance.id"], name="fk_balance_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ml_request_transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("balance_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["balance_id"], ["balance.id"], name="fk_balance_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_request_transaction")
    op.drop_table("deposit_transaction")
    # ### end Alembic commands ###
