"""Add deposit transaction model

Revision ID: de8ab54dc6dc
Revises: 46baad9e7249
Create Date: 2025-12-11 18:11:38.173248

"""

import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de8ab54dc6dc"
down_revision: Union[str, Sequence[str], None] = "46baad9e7249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("balance_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["balance_id"], ["balance.id"], name="fk_balance_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deposit_transaction")
    # ### end Alembic commands ###
